import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve('views');
const entries = [];

async function collect(directory) {
  for (const item of await readdir(directory, { withFileTypes: true })) {
    const target = path.join(directory, item.name);
    if (item.isDirectory()) await collect(target);
    else if (item.isFile() && item.name.endsWith('.ejs')) {
      const key = path.relative(root, target).split(path.sep).join('/');
      entries.push([key, await readFile(target, 'utf8')]);
    }
  }
}

await collect(root);
entries.sort(([a], [b]) => a.localeCompare(b));
const content = `// Generated by scripts/embed-views.mjs. Do not edit by hand.\nexport const generatedViews: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries))};\n`;
await writeFile('src/generated-views.ts', content, 'utf8');
